// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/bazueva/gofermart/internal/domain/entities"
	"github.com/bazueva/gofermart/internal/models"
	mock "github.com/stretchr/testify/mock"
)

// NewMockApp creates a new instance of MockApp. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockApp(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockApp {
	mock := &MockApp{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockApp is an autogenerated mock type for the App type
type MockApp struct {
	mock.Mock
}

type MockApp_Expecter struct {
	mock *mock.Mock
}

func (_m *MockApp) EXPECT() *MockApp_Expecter {
	return &MockApp_Expecter{mock: &_m.Mock}
}

// BalanceWithDraw provides a mock function for the type MockApp
func (_mock *MockApp) BalanceWithDraw(ctx context.Context, request models.BalanceWithdrawRequest) *entities.DomainError {
	ret := _mock.Called(ctx, request)

	if len(ret) == 0 {
		panic("no return value specified for BalanceWithDraw")
	}

	var r0 *entities.DomainError
	if returnFunc, ok := ret.Get(0).(func(context.Context, models.BalanceWithdrawRequest) *entities.DomainError); ok {
		r0 = returnFunc(ctx, request)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entities.DomainError)
		}
	}
	return r0
}

// MockApp_BalanceWithDraw_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'BalanceWithDraw'
type MockApp_BalanceWithDraw_Call struct {
	*mock.Call
}

// BalanceWithDraw is a helper method to define mock.On call
//   - ctx context.Context
//   - request models.BalanceWithdrawRequest
func (_e *MockApp_Expecter) BalanceWithDraw(ctx any, request any) *MockApp_BalanceWithDraw_Call {
	return &MockApp_BalanceWithDraw_Call{Call: _e.mock.On("BalanceWithDraw", ctx, request)}
}

func (_c *MockApp_BalanceWithDraw_Call) Run(run func(ctx context.Context, request models.BalanceWithdrawRequest)) *MockApp_BalanceWithDraw_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 models.BalanceWithdrawRequest
		if args[1] != nil {
			arg1 = args[1].(models.BalanceWithdrawRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockApp_BalanceWithDraw_Call) Return(domainError *entities.DomainError) *MockApp_BalanceWithDraw_Call {
	_c.Call.Return(domainError)
	return _c
}

func (_c *MockApp_BalanceWithDraw_Call) RunAndReturn(run func(ctx context.Context, request models.BalanceWithdrawRequest) *entities.DomainError) *MockApp_BalanceWithDraw_Call {
	_c.Call.Return(run)
	return _c
}

// CreateOrder provides a mock function for the type MockApp
func (_mock *MockApp) CreateOrder(ctx context.Context, id string) *entities.DomainError {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for CreateOrder")
	}

	var r0 *entities.DomainError
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *entities.DomainError); ok {
		r0 = returnFunc(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entities.DomainError)
		}
	}
	return r0
}

// MockApp_CreateOrder_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateOrder'
type MockApp_CreateOrder_Call struct {
	*mock.Call
}

// CreateOrder is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockApp_Expecter) CreateOrder(ctx any, id any) *MockApp_CreateOrder_Call {
	return &MockApp_CreateOrder_Call{Call: _e.mock.On("CreateOrder", ctx, id)}
}

func (_c *MockApp_CreateOrder_Call) Run(run func(ctx context.Context, id string)) *MockApp_CreateOrder_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockApp_CreateOrder_Call) Return(domainError *entities.DomainError) *MockApp_CreateOrder_Call {
	_c.Call.Return(domainError)
	return _c
}

func (_c *MockApp_CreateOrder_Call) RunAndReturn(run func(ctx context.Context, id string) *entities.DomainError) *MockApp_CreateOrder_Call {
	_c.Call.Return(run)
	return _c
}

// Login provides a mock function for the type MockApp
func (_mock *MockApp) Login(ctx context.Context, request models.LoginRequest) (string, *entities.DomainError) {
	ret := _mock.Called(ctx, request)

	if len(ret) == 0 {
		panic("no return value specified for Login")
	}

	var r0 string
	var r1 *entities.DomainError
	if returnFunc, ok := ret.Get(0).(func(context.Context, models.LoginRequest) (string, *entities.DomainError)); ok {
		return returnFunc(ctx, request)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, models.LoginRequest) string); ok {
		r0 = returnFunc(ctx, request)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, models.LoginRequest) *entities.DomainError); ok {
		r1 = returnFunc(ctx, request)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*entities.DomainError)
		}
	}
	return r0, r1
}

// MockApp_Login_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Login'
type MockApp_Login_Call struct {
	*mock.Call
}

// Login is a helper method to define mock.On call
//   - ctx context.Context
//   - request models.LoginRequest
func (_e *MockApp_Expecter) Login(ctx any, request any) *MockApp_Login_Call {
	return &MockApp_Login_Call{Call: _e.mock.On("Login", ctx, request)}
}

func (_c *MockApp_Login_Call) Run(run func(ctx context.Context, request models.LoginRequest)) *MockApp_Login_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 models.LoginRequest
		if args[1] != nil {
			arg1 = args[1].(models.LoginRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockApp_Login_Call) Return(s string, domainError *entities.DomainError) *MockApp_Login_Call {
	_c.Call.Return(s, domainError)
	return _c
}

func (_c *MockApp_Login_Call) RunAndReturn(run func(ctx context.Context, request models.LoginRequest) (string, *entities.DomainError)) *MockApp_Login_Call {
	_c.Call.Return(run)
	return _c
}

// Register provides a mock function for the type MockApp
func (_mock *MockApp) Register(ctx context.Context, request models.RegisterRequest) (string, *entities.DomainError) {
	ret := _mock.Called(ctx, request)

	if len(ret) == 0 {
		panic("no return value specified for Register")
	}

	var r0 string
	var r1 *entities.DomainError
	if returnFunc, ok := ret.Get(0).(func(context.Context, models.RegisterRequest) (string, *entities.DomainError)); ok {
		return returnFunc(ctx, request)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, models.RegisterRequest) string); ok {
		r0 = returnFunc(ctx, request)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, models.RegisterRequest) *entities.DomainError); ok {
		r1 = returnFunc(ctx, request)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*entities.DomainError)
		}
	}
	return r0, r1
}

// MockApp_Register_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Register'
type MockApp_Register_Call struct {
	*mock.Call
}

// Register is a helper method to define mock.On call
//   - ctx context.Context
//   - request models.RegisterRequest
func (_e *MockApp_Expecter) Register(ctx any, request any) *MockApp_Register_Call {
	return &MockApp_Register_Call{Call: _e.mock.On("Register", ctx, request)}
}

func (_c *MockApp_Register_Call) Run(run func(ctx context.Context, request models.RegisterRequest)) *MockApp_Register_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 models.RegisterRequest
		if args[1] != nil {
			arg1 = args[1].(models.RegisterRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockApp_Register_Call) Return(s string, domainError *entities.DomainError) *MockApp_Register_Call {
	_c.Call.Return(s, domainError)
	return _c
}

func (_c *MockApp_Register_Call) RunAndReturn(run func(ctx context.Context, request models.RegisterRequest) (string, *entities.DomainError)) *MockApp_Register_Call {
	_c.Call.Return(run)
	return _c
}

// UserOrdersList provides a mock function for the type MockApp
func (_mock *MockApp) UserOrdersList(ctx context.Context, page int32, perPage int32) ([]entities.Order, *entities.DomainError) {
	ret := _mock.Called(ctx, page, perPage)

	if len(ret) == 0 {
		panic("no return value specified for UserOrdersList")
	}

	var r0 []entities.Order
	var r1 *entities.DomainError
	if returnFunc, ok := ret.Get(0).(func(context.Context, int32, int32) ([]entities.Order, *entities.DomainError)); ok {
		return returnFunc(ctx, page, perPage)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int32, int32) []entities.Order); ok {
		r0 = returnFunc(ctx, page, perPage)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entities.Order)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int32, int32) *entities.DomainError); ok {
		r1 = returnFunc(ctx, page, perPage)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*entities.DomainError)
		}
	}
	return r0, r1
}

// MockApp_UserOrdersList_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UserOrdersList'
type MockApp_UserOrdersList_Call struct {
	*mock.Call
}

// UserOrdersList is a helper method to define mock.On call
//   - ctx context.Context
//   - page int32
//   - perPage int32
func (_e *MockApp_Expecter) UserOrdersList(ctx any, page any, perPage any) *MockApp_UserOrdersList_Call {
	return &MockApp_UserOrdersList_Call{Call: _e.mock.On("UserOrdersList", ctx, page, perPage)}
}

func (_c *MockApp_UserOrdersList_Call) Run(run func(ctx context.Context, page int32, perPage int32)) *MockApp_UserOrdersList_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int32
		if args[1] != nil {
			arg1 = args[1].(int32)
		}
		var arg2 int32
		if args[2] != nil {
			arg2 = args[2].(int32)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockApp_UserOrdersList_Call) Return(orders []entities.Order, domainError *entities.DomainError) *MockApp_UserOrdersList_Call {
	_c.Call.Return(orders, domainError)
	return _c
}

func (_c *MockApp_UserOrdersList_Call) RunAndReturn(run func(ctx context.Context, page int32, perPage int32) ([]entities.Order, *entities.DomainError)) *MockApp_UserOrdersList_Call {
	_c.Call.Return(run)
	return _c
}
