// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/bazueva/gofermart/internal/domain/entities"
	mock "github.com/stretchr/testify/mock"
)

// NewMockRepository creates a new instance of MockRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRepository {
	mock := &MockRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockRepository is an autogenerated mock type for the Repository type
type MockRepository struct {
	mock.Mock
}

type MockRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRepository) EXPECT() *MockRepository_Expecter {
	return &MockRepository_Expecter{mock: &_m.Mock}
}

// CreateOrder provides a mock function for the type MockRepository
func (_mock *MockRepository) CreateOrder(ctx context.Context, orderID string, userID int32, status entities.OrderStatus) *entities.DomainError {
	ret := _mock.Called(ctx, orderID, userID, status)

	if len(ret) == 0 {
		panic("no return value specified for CreateOrder")
	}

	var r0 *entities.DomainError
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, int32, entities.OrderStatus) *entities.DomainError); ok {
		r0 = returnFunc(ctx, orderID, userID, status)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entities.DomainError)
		}
	}
	return r0
}

// MockRepository_CreateOrder_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateOrder'
type MockRepository_CreateOrder_Call struct {
	*mock.Call
}

// CreateOrder is a helper method to define mock.On call
//   - ctx context.Context
//   - orderID string
//   - userID int32
//   - status entities.OrderStatus
func (_e *MockRepository_Expecter) CreateOrder(ctx any, orderID any, userID any, status any) *MockRepository_CreateOrder_Call {
	return &MockRepository_CreateOrder_Call{Call: _e.mock.On("CreateOrder", ctx, orderID, userID, status)}
}

func (_c *MockRepository_CreateOrder_Call) Run(run func(ctx context.Context, orderID string, userID int32, status entities.OrderStatus)) *MockRepository_CreateOrder_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 int32
		if args[2] != nil {
			arg2 = args[2].(int32)
		}
		var arg3 entities.OrderStatus
		if args[3] != nil {
			arg3 = args[3].(entities.OrderStatus)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockRepository_CreateOrder_Call) Return(domainError *entities.DomainError) *MockRepository_CreateOrder_Call {
	_c.Call.Return(domainError)
	return _c
}

func (_c *MockRepository_CreateOrder_Call) RunAndReturn(run func(ctx context.Context, orderID string, userID int32, status entities.OrderStatus) *entities.DomainError) *MockRepository_CreateOrder_Call {
	_c.Call.Return(run)
	return _c
}

// FindByOrderID provides a mock function for the type MockRepository
func (_mock *MockRepository) FindByOrderID(ctx context.Context, orderID string) (*entities.Order, *entities.DomainError) {
	ret := _mock.Called(ctx, orderID)

	if len(ret) == 0 {
		panic("no return value specified for FindByOrderID")
	}

	var r0 *entities.Order
	var r1 *entities.DomainError
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*entities.Order, *entities.DomainError)); ok {
		return returnFunc(ctx, orderID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *entities.Order); ok {
		r0 = returnFunc(ctx, orderID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entities.Order)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) *entities.DomainError); ok {
		r1 = returnFunc(ctx, orderID)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*entities.DomainError)
		}
	}
	return r0, r1
}

// MockRepository_FindByOrderID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByOrderID'
type MockRepository_FindByOrderID_Call struct {
	*mock.Call
}

// FindByOrderID is a helper method to define mock.On call
//   - ctx context.Context
//   - orderID string
func (_e *MockRepository_Expecter) FindByOrderID(ctx any, orderID any) *MockRepository_FindByOrderID_Call {
	return &MockRepository_FindByOrderID_Call{Call: _e.mock.On("FindByOrderID", ctx, orderID)}
}

func (_c *MockRepository_FindByOrderID_Call) Run(run func(ctx context.Context, orderID string)) *MockRepository_FindByOrderID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRepository_FindByOrderID_Call) Return(order *entities.Order, domainError *entities.DomainError) *MockRepository_FindByOrderID_Call {
	_c.Call.Return(order, domainError)
	return _c
}

func (_c *MockRepository_FindByOrderID_Call) RunAndReturn(run func(ctx context.Context, orderID string) (*entities.Order, *entities.DomainError)) *MockRepository_FindByOrderID_Call {
	_c.Call.Return(run)
	return _c
}
